name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Publish LIB
      run: dotnet publish Pla.Lib
    - name: Publish Shared
      run: dotnet publish Pla.Shared
    - name: Publish Gtk
      run: dotnet publish Pla.Gtk
 
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Pla.Lib/Pla.Lib.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}